### PR TITLE
Add delete entities api and impl `Clone` for Client

### PR DESCRIPTION
**Pull request by kingzcheung**
We need to implement Clone to extract the client in the web framework.

Signed-off-by: kingzcheung <kingzcheung@gmail.com>
see https://github.com/milvus-io/milvus-sdk-rust/issues/38

### CODE REVIEW

**Comment by kingzcheung** [comment]
see https://github.com/milvus-io/milvus-sdk-rust/issues/38

**Comment by yah01** [comment]
Hi @kingzcheung, lgtm but need to resolve the conflicts, look like you need to rebase the main branch.

**Comment by yah01** [comment]
Also please ensure only one commit in PR

**Comment by yah01** [comment]
resolve #38

**Review by yah01 — APPROVED** [review]
/lgtm

**Pull request merged**
